run_name: 'a2c-rmsprop-pong'

#env_id: 'SpaceInvaders-v0'
#env_id: '-v0'
#env_id: 'Riverraid-v0'
#env_id: 'Seaquest-v0'
env_id: 'Pong-v0'
#env_id: 'Frostbite-v0'
model_class: A2C
architecture: dqn_like

num_agents: !!int 16
num_agent_steps: !!int 5

output_dir: 'outputs'
logs_dir: 'tf_logs'
models_dir: 'models'
save_model_frequency: !!int 37035
max_checkpoints_to_keep: !!int 150
keep_checkpoint_every_n_hours: !!int 1

input_img_shape: !!python/tuple [84, 84]
num_input_images: !!int 4

max_grad_norm: !!float 0.5

optimizer: 'RMSProp'
momentum: !!float 0.0
rmsprop_decay: !!float 0.99

#min_initial_lr: !!float 0.0001
#max_initial_lr: !!float 0.01
min_initial_lr: !!float 0.0007
max_initial_lr: !!float 0.0007
decay_rate: !!float 0.96
decay_steps: !!int 30000

gamma: !!float 0.99
entropy_reg_value: !!float 0.01

value_loss_weight: !!float 0.5
policy_loss_weight: !!float 1.
